### ISSUE TITLE
App "Windmill" exists twice

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmillhub-issues#12]
1. https://hub.windmill.dev/apps/windmill
2. https://hub.windmill.dev/apps/Windmill (new)

All other apps only exists in their lower-cased version.

![Screenshot 2022-10-20 at 19-55-46 App windmillhub WindmillHub](https://user-images.githubusercontent.com/10872136/197022894-7ebc102a-51c8-42c9-895c-ae1a932d4399.png)

**Comment by rubenfiszel** [comment]
That's on me, I wrongly added the Go example with Windmill. I fixed it.

I will fix this permanently by lowercasing the app on submission
