### ISSUE TITLE
Integration's app page: HTTP 404

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmillhub-issues#18]
1. Go to https://hub.windmill.dev/integrations/mysql/ or any other integration page.
2. Click on "Apps".

![Screenshot_2023-01-20_17-32-01](https://user-images.githubusercontent.com/10872136/213752495-4ae6a8ca-e7eb-4a9d-b965-af4e22c078a2.png)

## Expected
An empty list of apps.

## Actual
![Screenshot_2023-01-20_17-32-56](https://user-images.githubusercontent.com/10872136/213752681-1d3be96f-98df-4750-a756-ff9ce113427e.png)

**Comment by rubenfiszel** [comment]
Fixed, thanks for the report
