### ISSUE TITLE
Minor HTTP 500 errors with resource type URLs

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmillhub-issues#2]
The following URLs return an HTTP 500, when they should return a rendered HTTP 404 page or redirect:

* https://hub.windmill.dev/resource_types/1/foo (app name does not fit the resource type in the database)
* https://hub.windmill.dev/resource_types/1 (no app name is given)

These URLs are not linked anywhere. I typed them into the address bar manually.

**Comment by rubenfiszel** [comment]
Fixed
