### ISSUE TITLE
Question: Can scripts persist files on disk?

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmillhub-issues#4]
This script suggestion asks to store a file in `/tmp`. I assume that scripts cannot persist data.

https://hub.windmill.dev/scripts/helper/27/download-file-to-tmp-helper

## Better script suggestion
* https://hub.windmill.dev/scripts/http/442/send-get-request-http
* Sends a GET HTTP requests and returns the response body to Windmill.

## Suggestion
* Mark script suggestion as invalid and less visible. (But still findable, if others have the same suggestion.)

**Comment by rubenfiszel** [comment]
Scripts can persist data under the form of internal state: https://docs.windmill.dev/docs/reference/#internal-state

But not on disk although I have some ideas about adding an option to execute the whole flow on the same worker and mount the same /tmp disk on all steps which would enable that

**Comment by rubenfiszel** [comment]
We will solve this through: https://github.com/windmill-labs/windmill/issues/577
