### ISSUE TITLE
Bug: Cannot edit app as a Windshaper

### ISSUE THREAD

**Issue by jaller94** [windmill-labs/windmillhub-issues#5]
## Steps to reproduce
1. Have a reputation of 4201
2. Go to https://hub.windmill.dev/apps/airtable
3. Click on "delete" underneath the "airtable" heading

## Expected
The app gets deleted, so that I can re-create it and give it a summary and description.

## Actual
The deletion is rejected with HTTP 403.
Also, my web interface thinks that I got logged out until I refresh the tab.

**Comment by rubenfiszel** [comment]
Fixed
